export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES";
export const GET_ALL_MESSAGES_SUCCESS = "GET_ALLM_ESSAGES_SUCCESS";
export const GET_ALL_MESSAGES_FAIL = "GET_ALL_MESSAGES_FAIL";
export const SEND_MESSAGES = "SEND_MESSAGES";
export const SEND_MESSAGES_SUCCESS = "SEND_MESSAGES_SUCCESS";
export const SEND_MESSAGES_FAIL = "SEND_MESSAGES_FAIL";
